#!/bin/bash


while [[ $# -gt 0 ]]
do
args="$1"

function help_menu {
    echo "Usage: abuseiplookup [-h] [-c|-r] ip_address [-o] [-iL file]"
    echo "Check or Get reports for IP address Abuse"
    echo "Options:"
    echo "  -c, --check   Check Abuse IP address"
    echo "  -r, --report  Get Abuse Reports for IP Address"
    echo "  -o, --only-abuse  Show only abusive IP"
    echo "  -iL, --input-file  Read IP from file"
    echo "  -h, --help    Show help message"
    exit
}



case $args in
    -h|--help)
    help_menu
    exit
    ;;
    -c|--check)
    ACTION="check"
    IP_ADDRESS="$2"
    shift 
    shift 
    ;;
    -r|--report)
    ACTION="report"
    IP_ADDRESS="$2"
    shift 
    shift 
    ;;
    -o|--only-abuse)
    ONLY_ABUSE=true
    shift
    ;;
    -iL|--input-file)
    IP_FILE="$2"
    shift 
    shift 
    ;;
    *)    
    echo "Unknown option: $args"
    help_menu
    exit 1
    ;;
esac
done

function request {
    curl -s -G https://api.abuseipdb.com/api/v2/$ACTION \
  --data-urlencode "ipAddress=$IP_ADDRESS" \
  -d maxAgeInDays=90 \
  -d verbose \
  -H "Key: $ABUSEIP_KEY" \
  -H "Accept: application/json"
} 

if [ -z "$IP_ADDRESS" ] && [ -z "$IP_FILE" ]; then
  echo "Check Help menu Please"
  exit 1
fi

if [ -n "$IP_ADDRESS" ] && [ -n "$IP_FILE" ]; then
  echo "Wooh: You Cannot use both IP address and IP file."
  echo "Usage: abuseiplookup [-h] [-c|-r] ip_address [-o] [-iL file]"
  exit 1
fi

if [ -n "$IP_FILE" ]; then
  if [ ! -f "$IP_FILE" ]; then
    echo "Error: IP file not found."
    exit 1
  fi

  while read IP_ADDRESS; do
    if [ "$ONLY_ABUSE" = true ]; then
      request | jq '.data | select(.abuseConfidenceScore == 100) | {ipAddress: .ipAddress, abuseConfidenceScore: .abuseConfidenceScore, domain: .domain, hostnames: .hostnames, countryCode: .countryCode, usageType: .usageType}'
    else
      request
    fi
    echo ""
  done < "$IP_FILE"
else
  if [ "$ACTION" == "check" ]; then
      request
      if [ "$ONLY_ABUSE" = true ]; then
      request | jq '.data | select(.abuseConfidenceScore == 100) | {ipAddress: .ipAddress, abuseConfidenceScore: .abuseConfidenceScore, domain: .domain, hostnames: .hostnames, countryCode: .countryCode, usageType: .usageType}'
    else
      request
    fi
  elif [ "$ACTION" == "report" ]; then
      request
  fi
fi
